// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplaySmall

#include "ui.h"

void ButtonPayNow1Click(lv_event_t * e)
{
	// Your code here
}

void ButtonPinOneClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinTwoClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinThreeClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinFourClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinFiveClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinSixClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinSevenClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinEightClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinNineClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinZeroClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinCancelClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinOKClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonConfigSaveAndExitClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonTestRelay1Clicked(lv_event_t * e)
{
	// Your code here
}

void HideQRCode(lv_event_t * e)
{
	// Your code here
}

void AddQRCode(lv_event_t * e)
{
	// Your code here
}

void CheckSECRETPin(lv_event_t * e)
{
	// Your code here
}

void ButtonLEDgreenClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonLEDblueClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonLEDredClicked(lv_event_t * e)
{
	// Your code here
}
