// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#ifndef _TOUCHDISPLAY_UI_H
#define _TOUCHDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenStart
void ui_ScreenStart_screen_init(void);
void ui_event_ScreenStart(lv_event_t * e);
extern lv_obj_t * ui_ScreenStart;
extern lv_obj_t * ui_TopScreen2;
extern lv_obj_t * ui_LabelTopScreen2;
void ui_event_ButtonGotoScreenPin(lv_event_t * e);
extern lv_obj_t * ui_ButtonGotoScreenPin;
extern lv_obj_t * ui_LabelButtonGotoScreenPin;
void ui_event_ButtonGotoScreenPin1(lv_event_t * e);
extern lv_obj_t * ui_ButtonGotoScreenPin1;
extern lv_obj_t * ui_LabelButtonGotoScreenPin1;
// SCREEN: ui_ScreenPIN
void ui_ScreenPIN_screen_init(void);
void ui_event_ScreenPIN(lv_event_t * e);
extern lv_obj_t * ui_ScreenPIN;
extern lv_obj_t * ui_TopScreen3;
extern lv_obj_t * ui_LabelTopScreen3;
extern lv_obj_t * ui_LabelPINValue;
void ui_event_ButtonPin1(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin1;
extern lv_obj_t * ui_LabelButtonPin1;
void ui_event_ButtonPin2(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin2;
extern lv_obj_t * ui_LabelButtonPin2;
void ui_event_ButtonPin3(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin3;
extern lv_obj_t * ui_LabelButtonPin3;
void ui_event_ButtonPin4(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin4;
extern lv_obj_t * ui_LabelButtonPin4;
void ui_event_ButtonPin5(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin5;
extern lv_obj_t * ui_LabelButtonPin5;
void ui_event_ButtonPin6(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin6;
extern lv_obj_t * ui_LabelButtonPin6;
void ui_event_ButtonPin7(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin7;
extern lv_obj_t * ui_LabelButtonPin7;
void ui_event_ButtonPin8(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin8;
extern lv_obj_t * ui_LabelButtonPin8;
void ui_event_ButtonPin9(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin9;
extern lv_obj_t * ui_LabelButtonPin9;
void ui_event_ButtonPin10(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin10;
extern lv_obj_t * ui_LabelButtonPin10;
void ui_event_ButtonPin11(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin11;
extern lv_obj_t * ui_LabelButtonPin11;
void ui_event_ButtonPin12(lv_event_t * e);
extern lv_obj_t * ui_ButtonPin12;
extern lv_obj_t * ui_LabelButtonPin12;
// SCREEN: ui_ScreenConfig
void ui_ScreenConfig_screen_init(void);
void ui_event_ScreenConfig(lv_event_t * e);
extern lv_obj_t * ui_ScreenConfig;
extern lv_obj_t * ui_TopScreen1;
extern lv_obj_t * ui_LabelTopScreen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_TextAreaConfigHost(lv_event_t * e);
extern lv_obj_t * ui_TextAreaConfigHost;
extern lv_obj_t * ui_LabelConfigHost;
void ui_event_TextAreaConfigDeviceID(lv_event_t * e);
extern lv_obj_t * ui_TextAreaConfigDeviceID;
extern lv_obj_t * ui_LabelConfigDeviceID;
void ui_event_TextAreaConfigDeviceKey(lv_event_t * e);
extern lv_obj_t * ui_TextAreaConfigDeviceKey;
extern lv_obj_t * ui_LabelConfigDeviceKey;
void ui_event_TextAreaConfigPin(lv_event_t * e);
extern lv_obj_t * ui_TextAreaConfigPin;
extern lv_obj_t * ui_LabelConfigPin;
void ui_event_ButtonGotoScreenStart(lv_event_t * e);
extern lv_obj_t * ui_ButtonGotoScreenStart;
extern lv_obj_t * ui_LabelButtonGotoScreenStart;
void ui_event_ButtonConfigSave(lv_event_t * e);
extern lv_obj_t * ui_ButtonConfigSave;
extern lv_obj_t * ui_LabelButtonConfigSave;
void ui_event_KeyboardText(lv_event_t * e);
extern lv_obj_t * ui_KeyboardText;
void ui_event_KeyboardNumber(lv_event_t * e);
extern lv_obj_t * ui_KeyboardNumber;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
