// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ButtonPayNow1Click(lv_event_t * e);
void ButtonPayNow2Click(lv_event_t * e);
void ButtonPinOneClicked(lv_event_t * e);
void ButtonPinTwoClicked(lv_event_t * e);
void ButtonPinThreeClicked(lv_event_t * e);
void ButtonPinFourClicked(lv_event_t * e);
void ButtonPinFiveClicked(lv_event_t * e);
void ButtonPinSixClicked(lv_event_t * e);
void ButtonPinSevenClicked(lv_event_t * e);
void ButtonPinEightClicked(lv_event_t * e);
void ButtonPinNineClicked(lv_event_t * e);
void ButtonPinZeroClicked(lv_event_t * e);
void ButtonPinCancelClicked(lv_event_t * e);
void ButtonPinOKClicked(lv_event_t * e);
void ButtonConfigSaveAndExitClicked(lv_event_t * e);
void ButtonTestRelay1Clicked(lv_event_t * e);
void ButtonTestRelay2Clicked(lv_event_t * e);
void ButtonLEDgreenClicked(lv_event_t * e);
void ButtonLEDblueClicked(lv_event_t * e);
void ButtonLEDredClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
