// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: ProjektButton

#include "ui.h"
#include "globals.h"

void ButtonKlick(lv_event_t * e)
{
	// Your code here
	toggleBit();
}

void ButtonConfigSave(lv_event_t * e)
{
	// Your code here
	const char *lnbitshost = lv_textarea_get_text(ui_TextAreaConfigHost);
	const char *deviceid = lv_textarea_get_text(ui_TextAreaConfigDeviceID);
	const char *devicekey = lv_textarea_get_text(ui_TextAreaConfigDeviceKey);
	const char *configpin = lv_textarea_get_text(ui_TextAreaConfigPin);
	editConfig(lnbitshost, deviceid, devicekey, configpin);
}
