// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#include "ui.h"

void ButtonKlick(lv_event_t * e)
{
	// Your code here
}

void ButtonPinOneClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinTwoClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinThreeClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinFourClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinFiveClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinSixClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinSevenClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinEightClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinNineClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinZeroClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinCancelClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonPinOKClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonConfigSave(lv_event_t * e)
{
	// Your code here
}
