// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: ProjektButton

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 167);
    lv_obj_set_height(ui_Button1, 108);
    lv_obj_set_x(ui_Button1, 2);
    lv_obj_set_y(ui_Button1, -171);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xE5FE5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xF5FD00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0xF9F14B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Button1, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Button1, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Klick mich");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaConfigHost = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextAreaConfigHost, 150);
    lv_obj_set_height(ui_TextAreaConfigHost, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaConfigHost, 56);
    lv_obj_set_y(ui_TextAreaConfigHost, -88);
    lv_obj_set_align(ui_TextAreaConfigHost, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaConfigHost, "legend.lnbits.com");
    lv_textarea_set_one_line(ui_TextAreaConfigHost, true);

    ui_LabelConfigHost = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelConfigHost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConfigHost, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelConfigHost, -80);
    lv_obj_set_y(ui_LabelConfigHost, -88);
    lv_obj_set_align(ui_LabelConfigHost, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConfigHost, "LNbitsHost:");
    lv_obj_set_style_text_color(ui_LabelConfigHost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConfigHost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaConfigDeviceID = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextAreaConfigDeviceID, 150);
    lv_obj_set_height(ui_TextAreaConfigDeviceID, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaConfigDeviceID, 56);
    lv_obj_set_y(ui_TextAreaConfigDeviceID, -44);
    lv_obj_set_align(ui_TextAreaConfigDeviceID, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaConfigDeviceID, "DeviceID");
    lv_textarea_set_one_line(ui_TextAreaConfigDeviceID, true);

    ui_LabelConfigDeviceID = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelConfigDeviceID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConfigDeviceID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConfigDeviceID, -80);
    lv_obj_set_y(ui_LabelConfigDeviceID, -44);
    lv_obj_set_align(ui_LabelConfigDeviceID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConfigDeviceID, "DeviceID:");
    lv_obj_set_style_text_color(ui_LabelConfigDeviceID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConfigDeviceID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaConfigDeviceKey = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextAreaConfigDeviceKey, 150);
    lv_obj_set_height(ui_TextAreaConfigDeviceKey, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaConfigDeviceKey, 57);
    lv_obj_set_y(ui_TextAreaConfigDeviceKey, 0);
    lv_obj_set_align(ui_TextAreaConfigDeviceKey, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaConfigDeviceKey, "DeviceKey");
    lv_textarea_set_one_line(ui_TextAreaConfigDeviceKey, true);

    ui_LabelConfigDeviceKey = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelConfigDeviceKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConfigDeviceKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConfigDeviceKey, -80);
    lv_obj_set_y(ui_LabelConfigDeviceKey, -1);
    lv_obj_set_align(ui_LabelConfigDeviceKey, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConfigDeviceKey, "DeviceKey:");
    lv_obj_set_style_text_color(ui_LabelConfigDeviceKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConfigDeviceKey, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaConfigPin = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextAreaConfigPin, 150);
    lv_obj_set_height(ui_TextAreaConfigPin, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaConfigPin, 57);
    lv_obj_set_y(ui_TextAreaConfigPin, 42);
    lv_obj_set_align(ui_TextAreaConfigPin, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaConfigPin, "Config PIN");
    lv_textarea_set_one_line(ui_TextAreaConfigPin, true);

    ui_LabelConfigPin = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelConfigPin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConfigPin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConfigPin, -80);
    lv_obj_set_y(ui_LabelConfigPin, 42);
    lv_obj_set_align(ui_LabelConfigPin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConfigPin, "ConfigPIN:");
    lv_obj_set_style_text_color(ui_LabelConfigPin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConfigPin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfigSave = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonConfigSave, 85);
    lv_obj_set_height(ui_ButtonConfigSave, 41);
    lv_obj_set_x(ui_ButtonConfigSave, 88);
    lv_obj_set_y(ui_ButtonConfigSave, 84);
    lv_obj_set_align(ui_ButtonConfigSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConfigSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConfigSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonConfigSave, lv_color_hex(0xAFACAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfigSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonConfigSave, lv_color_hex(0x131212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonConfigSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonConfigSave = lv_label_create(ui_ButtonConfigSave);
    lv_obj_set_width(ui_LabelButtonConfigSave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonConfigSave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonConfigSave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonConfigSave, "Save");

    ui_KeyboardText = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_KeyboardText, 320);
    lv_obj_set_height(ui_KeyboardText, 120);
    lv_obj_set_align(ui_KeyboardText, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardText, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_KeyboardNumber = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_KeyboardNumber, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardNumber, 320);
    lv_obj_set_height(ui_KeyboardNumber, 120);
    lv_obj_set_align(ui_KeyboardNumber, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardNumber, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaConfigHost, ui_event_TextAreaConfigHost, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaConfigDeviceID, ui_event_TextAreaConfigDeviceID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaConfigDeviceKey, ui_event_TextAreaConfigDeviceKey, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaConfigPin, ui_event_TextAreaConfigPin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonConfigSave, ui_event_ButtonConfigSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardText, ui_event_KeyboardText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardNumber, ui_event_KeyboardNumber, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
