// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: TouchDisplaySmall

#include "../ui.h"

void ui_ScreenWelcome_screen_init(void)
{
ui_ScreenWelcome = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenWelcome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenWelcome, lv_color_hex(0x0D3E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenWelcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopScreenConfigWelcome = lv_obj_create(ui_ScreenWelcome);
lv_obj_set_width( ui_TopScreenConfigWelcome, lv_pct(100));
lv_obj_set_height( ui_TopScreenConfigWelcome, lv_pct(10));
lv_obj_set_align( ui_TopScreenConfigWelcome, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_TopScreenConfigWelcome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TopScreenConfigWelcome, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TopScreenConfigWelcome, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopScreenConfigWelcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_TopScreenConfigWelcome, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTopScreenWelcome = lv_label_create(ui_TopScreenConfigWelcome);
lv_obj_set_width( ui_LabelTopScreenWelcome, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTopScreenWelcome, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTopScreenWelcome, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTopScreenWelcome,"Set up welcome");
lv_obj_set_style_text_color(ui_LabelTopScreenWelcome, lv_color_hex(0x0D3E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTopScreenWelcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_LabelTopScreenWelcome, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_LabelTopScreenWelcome, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTopScreenWelcome, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWelcome = lv_label_create(ui_ScreenWelcome);
lv_obj_set_width( ui_LabelWelcome, LV_SIZE_CONTENT);  /// -95
lv_obj_set_height( ui_LabelWelcome, LV_SIZE_CONTENT);   /// 3
lv_obj_set_x( ui_LabelWelcome, -103 );
lv_obj_set_y( ui_LabelWelcome, -170 );
lv_obj_set_align( ui_LabelWelcome, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWelcome,"Welcome");
lv_obj_set_style_text_color(ui_LabelWelcome, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWelcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LabelWelcome, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWelcome, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaWelcome1 = lv_textarea_create(ui_ScreenWelcome);
lv_obj_set_width( ui_TextAreaWelcome1, 200);
lv_obj_set_height( ui_TextAreaWelcome1, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_TextAreaWelcome1, 48 );
lv_obj_set_y( ui_TextAreaWelcome1, -130 );
lv_obj_set_align( ui_TextAreaWelcome1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaWelcome1,"Your choise");
lv_textarea_set_one_line(ui_TextAreaWelcome1,true);



ui_TextAreaWelcome2 = lv_textarea_create(ui_ScreenWelcome);
lv_obj_set_width( ui_TextAreaWelcome2, 200);
lv_obj_set_height( ui_TextAreaWelcome2, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_TextAreaWelcome2, 48 );
lv_obj_set_y( ui_TextAreaWelcome2, -88 );
lv_obj_set_align( ui_TextAreaWelcome2, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextAreaWelcome2,"Your choise");
lv_textarea_set_one_line(ui_TextAreaWelcome2,true);



ui_LabelWelcome1 = lv_label_create(ui_ScreenWelcome);
lv_obj_set_width( ui_LabelWelcome1, LV_SIZE_CONTENT);  /// -95
lv_obj_set_height( ui_LabelWelcome1, LV_SIZE_CONTENT);   /// 3
lv_obj_set_x( ui_LabelWelcome1, -105 );
lv_obj_set_y( ui_LabelWelcome1, -130 );
lv_obj_set_align( ui_LabelWelcome1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWelcome1,"Message 1:");
lv_obj_set_style_text_color(ui_LabelWelcome1, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWelcome1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWelcome2 = lv_label_create(ui_ScreenWelcome);
lv_obj_set_width( ui_LabelWelcome2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWelcome2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWelcome2, -105 );
lv_obj_set_y( ui_LabelWelcome2, -88 );
lv_obj_set_align( ui_LabelWelcome2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWelcome2,"Message 2:");
lv_obj_set_style_text_color(ui_LabelWelcome2, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWelcome2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWelcomeInfo = lv_label_create(ui_ScreenWelcome);
lv_obj_set_width( ui_LabelWelcomeInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWelcomeInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWelcomeInfo, 0 );
lv_obj_set_y( ui_LabelWelcomeInfo, -28 );
lv_obj_set_align( ui_LabelWelcomeInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWelcomeInfo,"It is only one option\nLeave blank for the default message");
lv_obj_set_style_text_color(ui_LabelWelcomeInfo, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWelcomeInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelWelcomeInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonGoConfigFromWelcome = lv_btn_create(ui_ScreenWelcome);
lv_obj_set_width( ui_ButtonGoConfigFromWelcome, 120);
lv_obj_set_height( ui_ButtonGoConfigFromWelcome, 41);
lv_obj_set_x( ui_ButtonGoConfigFromWelcome, -70 );
lv_obj_set_y( ui_ButtonGoConfigFromWelcome, 207 );
lv_obj_set_align( ui_ButtonGoConfigFromWelcome, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonGoConfigFromWelcome, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonGoConfigFromWelcome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonGoConfigFromWelcome, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonGoConfigFromWelcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonGoConfigFromWelcome, lv_color_hex(0x131212), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonGoConfigFromWelcome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonGoConfigFromWelcome, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonGoConfigFromWelcome, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelButtonGoConfig1 = lv_label_create(ui_ButtonGoConfigFromWelcome);
lv_obj_set_width( ui_LabelButtonGoConfig1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelButtonGoConfig1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelButtonGoConfig1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelButtonGoConfig1,"Config");
lv_obj_set_style_text_color(ui_LabelButtonGoConfig1, lv_color_hex(0x0D3E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelButtonGoConfig1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelButtonGoConfig1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KeyboardWelcome = lv_keyboard_create(ui_ScreenWelcome);
lv_obj_set_width( ui_KeyboardWelcome, 320);
lv_obj_set_height( ui_KeyboardWelcome, 170);
lv_obj_set_align( ui_KeyboardWelcome, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_KeyboardWelcome, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_TextAreaWelcome1, ui_event_TextAreaWelcome1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaWelcome2, ui_event_TextAreaWelcome2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonGoConfigFromWelcome, ui_event_ButtonGoConfigFromWelcome, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_KeyboardWelcome, ui_event_KeyboardWelcome, LV_EVENT_ALL, NULL);

}
