// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#include "../ui.h"

void ui_ScreenScan_screen_init(void)
{
    ui_ScreenScan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenScan, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopScreenScan = lv_obj_create(ui_ScreenScan);
    lv_obj_set_width(ui_TopScreenScan, lv_pct(100));
    lv_obj_set_height(ui_TopScreenScan, lv_pct(10));
    lv_obj_set_align(ui_TopScreenScan, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopScreenScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopScreenScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopScreenScan, lv_color_hex(0x828284), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopScreenScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TopScreenScan, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTopScreenScan = lv_label_create(ui_TopScreenScan);
    lv_obj_set_width(ui_LabelTopScreenScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTopScreenScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTopScreenScan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTopScreenScan, "ScreenScan");
    lv_obj_set_style_text_color(ui_LabelTopScreenScan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTopScreenScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTopScreenScan, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGotoScreenPin2 = lv_btn_create(ui_ScreenScan);
    lv_obj_set_width(ui_ButtonGotoScreenPin2, 100);
    lv_obj_set_height(ui_ButtonGotoScreenPin2, 50);
    lv_obj_set_x(ui_ButtonGotoScreenPin2, 59);
    lv_obj_set_y(ui_ButtonGotoScreenPin2, 205);
    lv_obj_set_align(ui_ButtonGotoScreenPin2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGotoScreenPin2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGotoScreenPin2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGotoScreenPin2, lv_color_hex(0x386E41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGotoScreenPin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonGotoScreenPin2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonGotoScreenPin2 = lv_label_create(ui_ButtonGotoScreenPin2);
    lv_obj_set_width(ui_LabelButtonGotoScreenPin2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonGotoScreenPin2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonGotoScreenPin2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonGotoScreenPin2, "Back");
    lv_obj_set_style_text_color(ui_LabelButtonGotoScreenPin2, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonGotoScreenPin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonGotoScreenPin2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGotoScreenStart1 = lv_btn_create(ui_ScreenScan);
    lv_obj_set_width(ui_ButtonGotoScreenStart1, 100);
    lv_obj_set_height(ui_ButtonGotoScreenStart1, 50);
    lv_obj_set_x(ui_ButtonGotoScreenStart1, -61);
    lv_obj_set_y(ui_ButtonGotoScreenStart1, 206);
    lv_obj_set_align(ui_ButtonGotoScreenStart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGotoScreenStart1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGotoScreenStart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGotoScreenStart1, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGotoScreenStart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonGotoScreenStart1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonGotoScreenPin3 = lv_label_create(ui_ButtonGotoScreenStart1);
    lv_obj_set_width(ui_LabelButtonGotoScreenPin3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonGotoScreenPin3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonGotoScreenPin3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonGotoScreenPin3, "Back");
    lv_obj_set_style_text_color(ui_LabelButtonGotoScreenPin3, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonGotoScreenPin3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonGotoScreenPin3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageScanQRCodeBorder = lv_img_create(ui_ScreenScan);
    lv_img_set_src(ui_ImageScanQRCodeBorder, &ui_img_166440904);
    lv_obj_set_width(ui_ImageScanQRCodeBorder, LV_SIZE_CONTENT);   /// 274
    lv_obj_set_height(ui_ImageScanQRCodeBorder, LV_SIZE_CONTENT);    /// 274
    lv_obj_set_x(ui_ImageScanQRCodeBorder, 7);
    lv_obj_set_y(ui_ImageScanQRCodeBorder, 7);
    lv_obj_set_align(ui_ImageScanQRCodeBorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScanQRCodeBorder, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScanQRCodeBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelProduct = lv_label_create(ui_ScreenScan);
    lv_obj_set_width(ui_LabelProduct, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProduct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProduct, -3);
    lv_obj_set_y(ui_LabelProduct, -161);
    lv_obj_set_align(ui_LabelProduct, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProduct, "-Product-");
    lv_obj_set_style_text_color(ui_LabelProduct, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProduct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProduct, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonGotoScreenPin2, ui_event_ButtonGotoScreenPin2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGotoScreenStart1, ui_event_ButtonGotoScreenStart1, LV_EVENT_ALL, NULL);

}
