// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#include "../ui.h"

void ui_ScreenSwitch_screen_init(void)
{
    ui_ScreenSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSwitch, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopScreenConfig1 = lv_obj_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TopScreenConfig1, lv_pct(100));
    lv_obj_set_height(ui_TopScreenConfig1, lv_pct(10));
    lv_obj_set_align(ui_TopScreenConfig1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopScreenConfig1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopScreenConfig1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopScreenConfig1, lv_color_hex(0x828284), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopScreenConfig1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TopScreenConfig1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTopScreenSwitch = lv_label_create(ui_TopScreenConfig1);
    lv_obj_set_width(ui_LabelTopScreenSwitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTopScreenSwitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTopScreenSwitch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTopScreenSwitch, "Set up switches");
    lv_obj_set_style_text_color(ui_LabelTopScreenSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTopScreenSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTopScreenSwitch, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitch1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitch1, LV_SIZE_CONTENT);   /// -95
    lv_obj_set_height(ui_LabelSwitch1, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelSwitch1, -104);
    lv_obj_set_y(ui_LabelSwitch1, -158);
    lv_obj_set_align(ui_LabelSwitch1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitch1, "Switch 1");
    lv_obj_set_style_text_color(ui_LabelSwitch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelSwitch1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitch1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTestFunction = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelTestFunction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestFunction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTestFunction, -103);
    lv_obj_set_y(ui_LabelTestFunction, 138);
    lv_obj_set_align(ui_LabelTestFunction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestFunction, "Test function:");
    lv_obj_set_style_text_color(ui_LabelTestFunction, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestFunction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelTestFunction, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTestRelay1 = lv_btn_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_ButtonTestRelay1, 95);
    lv_obj_set_height(ui_ButtonTestRelay1, 43);
    lv_obj_set_x(ui_ButtonTestRelay1, 0);
    lv_obj_set_y(ui_ButtonTestRelay1, 151);
    lv_obj_set_align(ui_ButtonTestRelay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTestRelay1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTestRelay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonTestRelay1, lv_color_hex(0xE5FE5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTestRelay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTestRelay1, lv_color_hex(0xF5FD00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonTestRelay1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_ButtonTestRelay1, lv_color_hex(0xF9F14B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ButtonTestRelay1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ButtonTestRelay1, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ButtonTestRelay1, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelTestRelay1 = lv_label_create(ui_ButtonTestRelay1);
    lv_obj_set_width(ui_LabelTestRelay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestRelay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTestRelay1, -1);
    lv_obj_set_y(ui_LabelTestRelay1, 0);
    lv_obj_set_align(ui_LabelTestRelay1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestRelay1, "Switch 1");
    lv_obj_set_style_text_color(ui_LabelTestRelay1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestRelay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTestRelay1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTestRelay2 = lv_btn_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_ButtonTestRelay2, 95);
    lv_obj_set_height(ui_ButtonTestRelay2, 43);
    lv_obj_set_x(ui_ButtonTestRelay2, 99);
    lv_obj_set_y(ui_ButtonTestRelay2, 151);
    lv_obj_set_align(ui_ButtonTestRelay2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTestRelay2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTestRelay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonTestRelay2, lv_color_hex(0xE5FE5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTestRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTestRelay2, lv_color_hex(0xF5FD00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonTestRelay2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_ButtonTestRelay2, lv_color_hex(0xF9F14B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ButtonTestRelay2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ButtonTestRelay2, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ButtonTestRelay2, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelTestRelay2 = lv_label_create(ui_ButtonTestRelay2);
    lv_obj_set_width(ui_LabelTestRelay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestRelay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTestRelay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestRelay2, "Switch 2");
    lv_obj_set_style_text_color(ui_LabelTestRelay2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTestRelay2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchName1 = lv_textarea_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TextAreaSwitchName1, 200);
    lv_obj_set_height(ui_TextAreaSwitchName1, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchName1, 48);
    lv_obj_set_y(ui_TextAreaSwitchName1, -130);
    lv_obj_set_align(ui_TextAreaSwitchName1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchName1, "Your choise");
    lv_textarea_set_one_line(ui_TextAreaSwitchName1, true);

    ui_LabelSwitchName1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitchName1, LV_SIZE_CONTENT);   /// -95
    lv_obj_set_height(ui_LabelSwitchName1, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelSwitchName1, -105);
    lv_obj_set_y(ui_LabelSwitchName1, -130);
    lv_obj_set_align(ui_LabelSwitchName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchName1, "Name:");
    lv_obj_set_style_text_color(ui_LabelSwitchName1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchTime1 = lv_textarea_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TextAreaSwitchTime1, 200);
    lv_obj_set_height(ui_TextAreaSwitchTime1, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchTime1, 48);
    lv_obj_set_y(ui_TextAreaSwitchTime1, -88);
    lv_obj_set_align(ui_TextAreaSwitchTime1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchTime1, "Time in ms");
    lv_textarea_set_one_line(ui_TextAreaSwitchTime1, true);

    ui_LabelSwitchTime1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitchTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchTime1, -105);
    lv_obj_set_y(ui_LabelSwitchTime1, -88);
    lv_obj_set_align(ui_LabelSwitchTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchTime1, "Time:");
    lv_obj_set_style_text_color(ui_LabelSwitchTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchRelay1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitchRelay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchRelay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchRelay1, -105);
    lv_obj_set_y(ui_LabelSwitchRelay1, -46);
    lv_obj_set_align(ui_LabelSwitchRelay1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchRelay1, "GPIO:");
    lv_obj_set_style_text_color(ui_LabelSwitchRelay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchRelay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchRelay1 = lv_textarea_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TextAreaSwitchRelay1, 200);
    lv_obj_set_height(ui_TextAreaSwitchRelay1, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchRelay1, 48);
    lv_obj_set_y(ui_TextAreaSwitchRelay1, -47);
    lv_obj_set_align(ui_TextAreaSwitchRelay1, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaSwitchRelay1, 6);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchRelay1, "21 (Is currently fixed)");
    lv_textarea_set_one_line(ui_TextAreaSwitchRelay1, true);
    lv_obj_clear_flag(ui_TextAreaSwitchRelay1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TextAreaSwitchRelay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaSwitchRelay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaSwitchRelay1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaSwitchRelay1, lv_color_hex(0x934646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaSwitchRelay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfigSave1 = lv_btn_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_ButtonConfigSave1, 120);
    lv_obj_set_height(ui_ButtonConfigSave1, 41);
    lv_obj_set_x(ui_ButtonConfigSave1, 72);
    lv_obj_set_y(ui_ButtonConfigSave1, 207);
    lv_obj_set_align(ui_ButtonConfigSave1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConfigSave1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConfigSave1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonConfigSave1, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfigSave1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonConfigSave1, lv_color_hex(0x131212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonConfigSave1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonConfigSave1, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonConfigSave1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelButtonConfigSave1 = lv_label_create(ui_ButtonConfigSave1);
    lv_obj_set_width(ui_LabelButtonConfigSave1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonConfigSave1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonConfigSave1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonConfigSave1, "Save+Exit");
    lv_obj_set_style_text_font(ui_LabelButtonConfigSave1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardText1 = lv_keyboard_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_KeyboardText1, 320);
    lv_obj_set_height(ui_KeyboardText1, 120);
    lv_obj_set_align(ui_KeyboardText1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardText1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_KeyboardNumber1 = lv_keyboard_create(ui_ScreenSwitch);
    lv_keyboard_set_mode(ui_KeyboardNumber1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardNumber1, 320);
    lv_obj_set_height(ui_KeyboardNumber1, 120);
    lv_obj_set_align(ui_KeyboardNumber1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardNumber1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ButtonGoConfig = lv_btn_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_ButtonGoConfig, 120);
    lv_obj_set_height(ui_ButtonGoConfig, 41);
    lv_obj_set_x(ui_ButtonGoConfig, -64);
    lv_obj_set_y(ui_ButtonGoConfig, 207);
    lv_obj_set_align(ui_ButtonGoConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGoConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGoConfig, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGoConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonGoConfig, lv_color_hex(0x131212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonGoConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGoConfig, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonGoConfig, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelButtonGoConfig = lv_label_create(ui_ButtonGoConfig);
    lv_obj_set_width(ui_LabelButtonGoConfig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonGoConfig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonGoConfig, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonGoConfig, "Config");
    lv_obj_set_style_text_font(ui_LabelButtonGoConfig, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitch2 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitch2, LV_SIZE_CONTENT);   /// -95
    lv_obj_set_height(ui_LabelSwitch2, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelSwitch2, -104);
    lv_obj_set_y(ui_LabelSwitch2, -13);
    lv_obj_set_align(ui_LabelSwitch2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitch2, "Switch 2");
    lv_obj_set_style_text_color(ui_LabelSwitch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelSwitch2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitch2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchName2 = lv_textarea_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TextAreaSwitchName2, 200);
    lv_obj_set_height(ui_TextAreaSwitchName2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchName2, 49);
    lv_obj_set_y(ui_TextAreaSwitchName2, 14);
    lv_obj_set_align(ui_TextAreaSwitchName2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchName2, "Your choise");
    lv_textarea_set_one_line(ui_TextAreaSwitchName2, true);

    ui_TextAreaSwitchTime2 = lv_textarea_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TextAreaSwitchTime2, 200);
    lv_obj_set_height(ui_TextAreaSwitchTime2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchTime2, 49);
    lv_obj_set_y(ui_TextAreaSwitchTime2, 56);
    lv_obj_set_align(ui_TextAreaSwitchTime2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchTime2, "Time in ms");
    lv_textarea_set_one_line(ui_TextAreaSwitchTime2, true);

    ui_TextAreaSwitchRelay2 = lv_textarea_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_TextAreaSwitchRelay2, 200);
    lv_obj_set_height(ui_TextAreaSwitchRelay2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchRelay2, 49);
    lv_obj_set_y(ui_TextAreaSwitchRelay2, 98);
    lv_obj_set_align(ui_TextAreaSwitchRelay2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaSwitchRelay2, 6);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchRelay2, "22 (Is currently fixed)");
    lv_textarea_set_one_line(ui_TextAreaSwitchRelay2, true);
    lv_obj_clear_flag(ui_TextAreaSwitchRelay2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TextAreaSwitchRelay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaSwitchRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaSwitchRelay2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaSwitchRelay2, lv_color_hex(0x934646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaSwitchRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchName2 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitchName2, LV_SIZE_CONTENT);   /// -95
    lv_obj_set_height(ui_LabelSwitchName2, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelSwitchName2, -106);
    lv_obj_set_y(ui_LabelSwitchName2, 19);
    lv_obj_set_align(ui_LabelSwitchName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchName2, "Name:");
    lv_obj_set_style_text_color(ui_LabelSwitchName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchTime2 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitchTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchTime2, -104);
    lv_obj_set_y(ui_LabelSwitchTime2, 55);
    lv_obj_set_align(ui_LabelSwitchTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchTime2, "Time:");
    lv_obj_set_style_text_color(ui_LabelSwitchTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchRelay2 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelSwitchRelay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchRelay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchRelay2, -104);
    lv_obj_set_y(ui_LabelSwitchRelay2, 96);
    lv_obj_set_align(ui_LabelSwitchRelay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchRelay2, "GPIO:");
    lv_obj_set_style_text_color(ui_LabelSwitchRelay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonTestRelay1, ui_event_ButtonTestRelay1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTestRelay2, ui_event_ButtonTestRelay2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchName1, ui_event_TextAreaSwitchName1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchTime1, ui_event_TextAreaSwitchTime1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchRelay1, ui_event_TextAreaSwitchRelay1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonConfigSave1, ui_event_ButtonConfigSave1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardText1, ui_event_KeyboardText1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardNumber1, ui_event_KeyboardNumber1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoConfig, ui_event_ButtonGoConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchName2, ui_event_TextAreaSwitchName2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchTime2, ui_event_TextAreaSwitchTime2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchRelay2, ui_event_TextAreaSwitchRelay2, LV_EVENT_ALL, NULL);

}
