// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#include "../ui.h"

void ui_ScreenQRCode_screen_init(void)
{
    ui_ScreenQRCode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenQRCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenQRCode, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenQRCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopScreenQRCode = lv_obj_create(ui_ScreenQRCode);
    lv_obj_set_width(ui_TopScreenQRCode, lv_pct(100));
    lv_obj_set_height(ui_TopScreenQRCode, lv_pct(10));
    lv_obj_set_align(ui_TopScreenQRCode, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopScreenQRCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopScreenQRCode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopScreenQRCode, lv_color_hex(0x828284), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopScreenQRCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TopScreenQRCode, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTopScreenQRCode = lv_label_create(ui_TopScreenQRCode);
    lv_obj_set_width(ui_LabelTopScreenQRCode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTopScreenQRCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTopScreenQRCode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTopScreenQRCode, "ScreenQRCode");
    lv_obj_set_style_text_color(ui_LabelTopScreenQRCode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTopScreenQRCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTopScreenQRCode, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGotoScreenPin2 = lv_btn_create(ui_ScreenQRCode);
    lv_obj_set_width(ui_ButtonGotoScreenPin2, 100);
    lv_obj_set_height(ui_ButtonGotoScreenPin2, 50);
    lv_obj_set_x(ui_ButtonGotoScreenPin2, 59);
    lv_obj_set_y(ui_ButtonGotoScreenPin2, 205);
    lv_obj_set_align(ui_ButtonGotoScreenPin2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGotoScreenPin2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGotoScreenPin2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGotoScreenPin2, lv_color_hex(0x386E41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGotoScreenPin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonGotoScreenPin2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonGotoScreenPin2 = lv_label_create(ui_ButtonGotoScreenPin2);
    lv_obj_set_width(ui_LabelButtonGotoScreenPin2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonGotoScreenPin2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonGotoScreenPin2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonGotoScreenPin2, "Back");
    lv_obj_set_style_text_color(ui_LabelButtonGotoScreenPin2, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonGotoScreenPin2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonGotoScreenPin2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGotoScreenStartQRCode = lv_btn_create(ui_ScreenQRCode);
    lv_obj_set_width(ui_ButtonGotoScreenStartQRCode, 100);
    lv_obj_set_height(ui_ButtonGotoScreenStartQRCode, 50);
    lv_obj_set_x(ui_ButtonGotoScreenStartQRCode, -62);
    lv_obj_set_y(ui_ButtonGotoScreenStartQRCode, 206);
    lv_obj_set_align(ui_ButtonGotoScreenStartQRCode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGotoScreenStartQRCode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGotoScreenStartQRCode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGotoScreenStartQRCode, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGotoScreenStartQRCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonGotoScreenStartQRCode, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonGotoScreenPin3 = lv_label_create(ui_ButtonGotoScreenStartQRCode);
    lv_obj_set_width(ui_LabelButtonGotoScreenPin3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonGotoScreenPin3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonGotoScreenPin3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonGotoScreenPin3, "Back");
    lv_obj_set_style_text_color(ui_LabelButtonGotoScreenPin3, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelButtonGotoScreenPin3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelButtonGotoScreenPin3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_ScreenQRCode);
    lv_img_set_src(ui_Image2, &ui_img_166440904);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 274
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 274
    lv_obj_set_x(ui_Image2, 11);
    lv_obj_set_y(ui_Image2, 8);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonGotoScreenPin2, ui_event_ButtonGotoScreenPin2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGotoScreenStartQRCode, ui_event_ButtonGotoScreenStartQRCode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenQRCode, ui_event_ScreenQRCode, LV_EVENT_ALL, NULL);

}
