// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: TouchDisplay

#include "../ui.h"

void ui_ScreenSwitch2_screen_init(void)
{
    ui_ScreenSwitch2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitch2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSwitch2, lv_color_hex(0x424344), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopScreenConfig2 = lv_obj_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_TopScreenConfig2, lv_pct(100));
    lv_obj_set_height(ui_TopScreenConfig2, lv_pct(10));
    lv_obj_set_align(ui_TopScreenConfig2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopScreenConfig2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopScreenConfig2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopScreenConfig2, lv_color_hex(0x828284), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopScreenConfig2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TopScreenConfig2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTopScreenSwitch1 = lv_label_create(ui_TopScreenConfig2);
    lv_obj_set_width(ui_LabelTopScreenSwitch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTopScreenSwitch1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTopScreenSwitch1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTopScreenSwitch1, "Set up switch 2");
    lv_obj_set_style_text_color(ui_LabelTopScreenSwitch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTopScreenSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTopScreenSwitch1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitch3 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_LabelSwitch3, LV_SIZE_CONTENT);   /// -95
    lv_obj_set_height(ui_LabelSwitch3, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelSwitch3, -104);
    lv_obj_set_y(ui_LabelSwitch3, -158);
    lv_obj_set_align(ui_LabelSwitch3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitch3, "Switch 2");
    lv_obj_set_style_text_color(ui_LabelSwitch3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelSwitch3, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitch3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTestFunction2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_LabelTestFunction2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestFunction2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTestFunction2, -103);
    lv_obj_set_y(ui_LabelTestFunction2, 138);
    lv_obj_set_align(ui_LabelTestFunction2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestFunction2, "Test function:");
    lv_obj_set_style_text_color(ui_LabelTestFunction2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestFunction2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LabelTestFunction2, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTestRelay2 = lv_btn_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_ButtonTestRelay2, 95);
    lv_obj_set_height(ui_ButtonTestRelay2, 43);
    lv_obj_set_x(ui_ButtonTestRelay2, 0);
    lv_obj_set_y(ui_ButtonTestRelay2, 151);
    lv_obj_set_align(ui_ButtonTestRelay2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTestRelay2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTestRelay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonTestRelay2, lv_color_hex(0xE5FE5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonTestRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonTestRelay2, lv_color_hex(0xF5FD00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonTestRelay2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_ButtonTestRelay2, lv_color_hex(0xF9F14B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ButtonTestRelay2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_ButtonTestRelay2, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_ButtonTestRelay2, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelTestRelay2 = lv_label_create(ui_ButtonTestRelay2);
    lv_obj_set_width(ui_LabelTestRelay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestRelay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTestRelay2, -1);
    lv_obj_set_y(ui_LabelTestRelay2, 0);
    lv_obj_set_align(ui_LabelTestRelay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestRelay2, "Switch 2");
    lv_obj_set_style_text_color(ui_LabelTestRelay2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTestRelay2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchName2 = lv_textarea_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_TextAreaSwitchName2, 200);
    lv_obj_set_height(ui_TextAreaSwitchName2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchName2, 48);
    lv_obj_set_y(ui_TextAreaSwitchName2, -130);
    lv_obj_set_align(ui_TextAreaSwitchName2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchName2, "Your choise");
    lv_textarea_set_one_line(ui_TextAreaSwitchName2, true);

    ui_LabelSwitchName2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_LabelSwitchName2, LV_SIZE_CONTENT);   /// -95
    lv_obj_set_height(ui_LabelSwitchName2, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_LabelSwitchName2, -105);
    lv_obj_set_y(ui_LabelSwitchName2, -130);
    lv_obj_set_align(ui_LabelSwitchName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchName2, "Name:");
    lv_obj_set_style_text_color(ui_LabelSwitchName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchPrice2 = lv_textarea_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_TextAreaSwitchPrice2, 200);
    lv_obj_set_height(ui_TextAreaSwitchPrice2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchPrice2, 48);
    lv_obj_set_y(ui_TextAreaSwitchPrice2, -90);
    lv_obj_set_align(ui_TextAreaSwitchPrice2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchPrice2, "1 for sat or 1.00 for EUR");
    lv_textarea_set_one_line(ui_TextAreaSwitchPrice2, true);

    ui_LabelSwitchPrice2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_LabelSwitchPrice2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchPrice2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchPrice2, -105);
    lv_obj_set_y(ui_LabelSwitchPrice2, -89);
    lv_obj_set_align(ui_LabelSwitchPrice2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchPrice2, "Price:");
    lv_obj_set_style_text_color(ui_LabelSwitchPrice2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchPrice2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchTime2 = lv_textarea_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_TextAreaSwitchTime2, 200);
    lv_obj_set_height(ui_TextAreaSwitchTime2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchTime2, 48);
    lv_obj_set_y(ui_TextAreaSwitchTime2, -49);
    lv_obj_set_align(ui_TextAreaSwitchTime2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchTime2, "Time in ms");
    lv_textarea_set_one_line(ui_TextAreaSwitchTime2, true);

    ui_LabelSwitchTime2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_LabelSwitchTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchTime2, -104);
    lv_obj_set_y(ui_LabelSwitchTime2, -49);
    lv_obj_set_align(ui_LabelSwitchTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchTime2, "Time:");
    lv_obj_set_style_text_color(ui_LabelSwitchTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSwitchRelay2 = lv_textarea_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_TextAreaSwitchRelay2, 200);
    lv_obj_set_height(ui_TextAreaSwitchRelay2, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaSwitchRelay2, 48);
    lv_obj_set_y(ui_TextAreaSwitchRelay2, -7);
    lv_obj_set_align(ui_TextAreaSwitchRelay2, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaSwitchRelay2, 6);
    lv_textarea_set_placeholder_text(ui_TextAreaSwitchRelay2, "21 (Is currently fixed)");
    lv_textarea_set_one_line(ui_TextAreaSwitchRelay2, true);
    lv_obj_clear_flag(ui_TextAreaSwitchRelay2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_TextAreaSwitchRelay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaSwitchRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaSwitchRelay2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextAreaSwitchRelay2, lv_color_hex(0x934646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextAreaSwitchRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchRelay2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_LabelSwitchRelay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchRelay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchRelay2, -101);
    lv_obj_set_y(ui_LabelSwitchRelay2, -6);
    lv_obj_set_align(ui_LabelSwitchRelay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchRelay2, "GPIO:");
    lv_obj_set_style_text_color(ui_LabelSwitchRelay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGotoSwitch1 = lv_btn_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_ButtonGotoSwitch1, 120);
    lv_obj_set_height(ui_ButtonGotoSwitch1, 41);
    lv_obj_set_x(ui_ButtonGotoSwitch1, 72);
    lv_obj_set_y(ui_ButtonGotoSwitch1, 207);
    lv_obj_set_align(ui_ButtonGotoSwitch1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGotoSwitch1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGotoSwitch1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGotoSwitch1, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGotoSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonGotoSwitch1, lv_color_hex(0x131212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonGotoSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGotoSwitch1, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonGotoSwitch1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelButtonConfigSave2 = lv_label_create(ui_ButtonGotoSwitch1);
    lv_obj_set_width(ui_LabelButtonConfigSave2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonConfigSave2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonConfigSave2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonConfigSave2, "Switch 1");
    lv_obj_set_style_text_font(ui_LabelButtonConfigSave2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoConfig1 = lv_btn_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_ButtonGoConfig1, 120);
    lv_obj_set_height(ui_ButtonGoConfig1, 41);
    lv_obj_set_x(ui_ButtonGoConfig1, -64);
    lv_obj_set_y(ui_ButtonGoConfig1, 207);
    lv_obj_set_align(ui_ButtonGoConfig1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGoConfig1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoConfig1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonGoConfig1, lv_color_hex(0xCFCFD7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGoConfig1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonGoConfig1, lv_color_hex(0x131212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonGoConfig1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGoConfig1, lv_color_hex(0x939393), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonGoConfig1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelButtonGoConfig1 = lv_label_create(ui_ButtonGoConfig1);
    lv_obj_set_width(ui_LabelButtonGoConfig1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonGoConfig1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonGoConfig1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonGoConfig1, "Config");
    lv_obj_set_style_text_font(ui_LabelButtonGoConfig1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardSwitchText2 = lv_keyboard_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_KeyboardSwitchText2, 320);
    lv_obj_set_height(ui_KeyboardSwitchText2, 120);
    lv_obj_set_align(ui_KeyboardSwitchText2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardSwitchText2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_KeyboardSwitchNumber2 = lv_keyboard_create(ui_ScreenSwitch2);
    lv_keyboard_set_mode(ui_KeyboardSwitchNumber2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardSwitchNumber2, 320);
    lv_obj_set_height(ui_KeyboardSwitchNumber2, 120);
    lv_obj_set_align(ui_KeyboardSwitchNumber2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_KeyboardSwitchNumber2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ButtonTestRelay2, ui_event_ButtonTestRelay2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchName2, ui_event_TextAreaSwitchName2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchPrice2, ui_event_TextAreaSwitchPrice2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchTime2, ui_event_TextAreaSwitchTime2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaSwitchRelay2, ui_event_TextAreaSwitchRelay2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGotoSwitch1, ui_event_ButtonGotoSwitch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoConfig1, ui_event_ButtonGoConfig1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardSwitchText2, ui_event_KeyboardSwitchText2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KeyboardSwitchNumber2, ui_event_KeyboardSwitchNumber2, LV_EVENT_ALL, NULL);

}
